---
title: "Introducción al procesamiento de datos con R"
authot: 
  - name: Pablo Tiscornia
site: distill::distill_website
---

## Presentación
  
El taller tiene como principal objetivo introducir a los y las integrantes de la Agencia de Acceso a la Información Pública en el mundo de la programación con R. El objetivo a alcanzar es centrarse en cómo encarar un proyecto que involucre diseñar y llevar a cabo un proyecto de trabajo con la información recolectada por la oficina, que va desde cómo nombrar las carpetas o archivos, leer los datos, limpiarlos, procesarlos hasta como visualizar, analizar y comunicar los hallazgos.

## ¿Para quién?

Equipo de trabajo de la Agencia de Acceso a la Información Pública.


## ¿Cómo?

Las clases del taller serán teórico-prácticas. Por cada presentación temática se plantearán ejercicios sobre lo visto, abordando al mismo tiempo las dudas que puedan surgir. Se priorizará la utilización del programa durante la clase y la aplicación práctica sobre los datos que produce el organismo.

## Cronograma: 

__Cantidad de encuentros:__ 5.

__Cantidad de horas por encuentro:__ 2hs.

__Día y horario de cursada:__ Miércoles, de 14:30 a 15:30hs y Viernes de 11 a 13hs.
  
__Fecha de inicio__: Miércoles 24 de Julio de 2024.

__Fecha de finalización__: Miércoles 7 de agosto de 2024

