---
title: "Puesta a punto"
description: |
  Instalación y ajustes para comenzar el curso
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Instrucciones de instalación de los programas R y Rstudio ^[Traducción del instructivo original diseñado por [Data Carpentry](https://datacarpentry.org/R-genomics/index.html)]


**R** y **RStudio** son descargas e instalaciones independientes. R es el entorno de cálculo estadístico subyacente, pero utilizar R por sí solo no es divertido. RStudio es un entorno gráfico de desarrollo integrado (IDE) que hace que el uso de R sea mucho más fácil e interactivo. Es necesario instalar R antes de instalar RStudio. Después de instalar ambos programas, tendrá que instalar el paquete `tidyverse` desde RStudio. En las siguientes secciones encontrará las instrucciones para instalar R y R Studio en su sistema operativo, así como las instrucciones para instalar a continuación `tidyverse`

<br>

*** 

### Windows

> Si ya tiene R y RStudio instalados

- Abra RStudio y haga clic en «Ayuda» > «Buscar actualizaciones». Si hay una nueva versión disponible, salga de RStudio, y descargue la última versión para RStudio.

- Para comprobar qué versión de R estás utilizando, inicia RStudio y lo primero que aparece en la consola indica la versión de R que estás ejecutando. Alternativamente, puedes escribir `sessionInfo()`, que también mostrará qué versión de R estás ejecutando. Vaya al sitio web de [CRAN](https://cran.r-project.org/bin/windows/base/) y compruebe si hay disponible una versión más reciente. Si es así, descárguela e instálela. Puede [consultar aquí](https://cran.r-project.org/bin/windows/base/rw-FAQ.html#How-do-I-UNinstall-R_003f) más información sobre cómo eliminar versiones antiguas de su sistema si lo desea.


> Si no tiene R y RStudio instalados

- Descargue R del sitio web [CRAN](cran.r-project.org/bin/windows/base/release.htm).

- Ejecute el archivo `.exe` que acaba de descargar

- Vaya a la [página de descarga de RStudio](https://www.rstudio.com/products/rstudio/download/#download)

- En `Installers` seleccione **RStudio x.yy.zzz - Windows XP/Vista/7/8** (donde x, y, y z representan números de versión)

- Haga doble clic en el archivo para instalarlo

- Una vez instalado, abre RStudio para asegurarte de que funciona y no recibes ningún mensaje de error.

<br>

*** 

### macOS

> Si ya tienes R y RStudio instalados

- Abre RStudio y haz clic en «Ayuda» > «Buscar actualizaciones». Si hay una nueva versión disponible, sal de RStudio, y descarga la última versión para RStudio.

- Para comprobar la versión de R que estás utilizando, inicia RStudio y lo primero que aparecerá en el terminal te indicará la versión de R que estás ejecutando. Alternativamente, puedes escribir `sessionInfo()`, que también mostrará qué versión de R estás ejecutando. Vaya al sitio web de [CRAN](https://cran.r-project.org/bin/macosx/) y compruebe si hay disponible una versión más reciente. Si es así, descárguela e instálela.


> Si no tiene R y RStudio instalados

- Descargue R del [sitio web CRAN](http://cran.r-project.org/bin/macosx).

- Seleccione el archivo `.pkg` para la última versión de R

- Haga doble clic en el archivo descargado para instalar R

- También es una buena idea instalar [XQuartz](https://www.xquartz.org/) (necesario para algunos paquetes)

- Vaya a la [página de descarga de RStudio](https://www.rstudio.com/products/rstudio/download/#download)

- En Instaladores seleccione **RStudio x.yy.zzz - Mac OS X 10.6+ (64-bit)** (donde x, y, y z representan números de versión)

- Haga doble clic en el archivo para instalar RStudio

- Una vez instalado, abre RStudio para asegurarte de que funciona y no recibes ningún mensaje de error.

<br>

*** 

### Linux

- Siga las instrucciones para su distribución desde [CRAN](https://cloud.r-project.org/bin/linux), proporcionan información para obtener la versión más reciente de R para las distribuciones comunes. Para la mayoría de las distribuciones, podrías utilizar tu gestor de paquetes (por ejemplo, para Debian/Ubuntu ejecuta `sudo apt-get install r-base`, y para Fedora `sudo yum install R`), pero no recomendamos este enfoque ya que las versiones proporcionadas por este suelen estar desactualizadas. En cualquier caso, asegúrate de que tienes al menos R 3.3.1.

- Vaya a la [página de descargas de RStudio](https://www.rstudio.com/products/rstudio/download/#download)

- En `Installers` seleccione la versión que coincida con su distribución, e instálela con su método preferido (por ejemplo, con Debian/Ubuntu `sudo dpkg -i rstudio-x.yy.zzz-amd64.deb` en el terminal).

- Una vez instalado, abre RStudio para asegurarte de que funciona y no recibes ningún mensaje de error.

<br>

## Para todos

**Después de instalar R y RStudio, necesitas instalar los paquetes `tidyverse`**

- Después de iniciar RStudio, en la consola escriba: `install.packages("tidyverse")`


## Descarga de Slack (versión escritorio)

En este curso vamos autilizar Slack, una plataforma de intercambio que funciona como un chat-foro. Desde allí es posible concentrar la comunicación del curso, difundir material, código como también realizar consultas y respuestas de forma grupal. [Aquí podes descargar](https://slack.com/intl/es-mx/downloads/l) la aplicación para tu sistema operativo.